apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: task031
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
- kind: ServiceAccount
  name: jane
  namespace: dev
  apiGroup: ""
