apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: task032
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view
subjects:
- kind: ServiceAccount
  name: ken
  apiGroup: ""
